# Generated by Django 5.2 on 2025-04-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste1Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teste1Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teste1Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOME FANTASIA')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='RAZÃO SOCIAL')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True, verbose_name='CNPJ')),
                ('insc_est', models.CharField(blank=True, max_length=25, null=True, verbose_name='INSC EST')),
                ('sigla_imp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA IMP')),
                ('sigla_exp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA EXP')),
                ('serv_sigla_imp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA IMP SERV')),
                ('serv_sigla_exp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA EXP SERV')),
                ('cod_interno', models.CharField(blank=True, max_length=25, null=True, verbose_name='COD INTERNO')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='OBSERVACOES')),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO')], max_length=2)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='operacional.teste1categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='operacional.teste1grupo')),
            ],
        ),
    ]
