# Generated by Django 5.2 on 2025-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste1cliente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='teste1cliente',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Teste1Categoria',
        ),
        migrations.DeleteModel(
            name='Teste1Cliente',
        ),
        migrations.DeleteModel(
            name='Teste1Grupo',
        ),
    ]
