# Generated by Django 5.2 on 2025-04-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste1TipoComex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO')], max_length=2)),
                ('empresa_grupo', models.CharField(choices=[('TD', 'TODAS'), ('PC', 'PLENO COMEX'), ('PS', 'PLENO SERVICOS'), ('LG', 'LOGISTICA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teste1ProcessoComex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'NÃO INICIADO'), ('E', 'EM ANDAMENTO'), ('A', 'A FATURAR'), ('F', 'FATURADO'), ('V', 'VERIFICAR'), ('C', 'CONCLUIDO')], default='N', max_length=2)),
                ('comex', models.CharField(choices=[('I', 'IMP'), ('E', 'EXP'), ('O', 'OUTRO')], default='I', max_length=2)),
                ('modal', models.CharField(choices=[('M', 'MARITIMO'), ('A', 'AEREO'), ('R', 'RODOVIARIO'), ('C', 'COURIER'), ('P', 'POSTAL'), ('O', 'OUTRO')], default='M', max_length=2)),
                ('data_abertura', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Abertura')),
                ('codigo_processo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo Processo')),
                ('ref_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref Cliente')),
                ('numero_alternativo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Alternativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='OBSERVACOES')),
                ('empresa_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Empresa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parceiros.teste1cliente')),
                ('empresa_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.teste1tipocomex')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
