# Generated by Django 5.2 on 2025-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste1processocomex',
            name='codigo_processo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo Processo'),
        ),
    ]
