# Generated by Django 5.2 on 2025-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_teste1processocomex_codigo_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste1processocomex',
            name='comex',
            field=models.CharField(choices=[('I', 'IMPORTAÇÃO'), ('E', 'EXPORTAÇÃO'), ('O', 'OUTRO')], default='I', max_length=2),
        ),
    ]
